### ISSUE TITLE
ITW destroys blue-channel when opening normal and specular maps

### ISSUE THREAD

**Issue by neokio** [GameTechDev/ITW-Beta-Test#8]
There's lots of chatter about this on various forums (including [this one](http://forums.nexusmods.com/index.php?/topic/3596925-nvidia-dds-tool-and-nifscope-settings-tutorial-and-presets/?p=32461660)).

Opening a normal or specular map with the nVidia pluging yields this:
![nvidia](https://cloud.githubusercontent.com/assets/146623/12697566/a625b82c-c787-11e5-8dd6-9ed0fd9fe20f.png)

Opening the same file with the ITW plugin yields this:
![intel](https://cloud.githubusercontent.com/assets/146623/12697571/b70657d2-c787-11e5-889b-abb495909f75.png)

Notice that the BLUE channel in the ITW is black.

**Comment by jawilli312** [comment]
Thanks. Please upload your source file.

**Comment by neokio** [comment]
Here's the file, direct from the Fallout 4 installation...

[RaiderHeadGear1_n.zip](https://github.com/GameTechDev/ITW-Beta-Test/files/111180/RaiderHeadGear1_n.zip)

**Comment by neokio** [comment]
Oops, that's the normal map ... it also loses its blue channel, but for sake of total clarity, here's the specular map as seen in the snapshots above:

[RaiderHeadGear1_s.zip](https://github.com/GameTechDev/ITW-Beta-Test/files/111182/RaiderHeadGear1_s.zip)

**Comment by ParasiteX** [comment]
It can't destroy the Blue channel. Because the normals and speculars in Fallout 4 does not use the blue channel.
ITW opens and saves the textures correctly. It's the nVidia plugin that doesn't know how to properly open them.
The Red channel in speculars handle Specular, while green channel handles Gloss.

**Comment by jawilli312** [comment]
The BC5 format is a 2 channel map in the [Microsoft Specification](https://msdn.microsoft.com/en-us/library/windows/desktop/bb694531%28v=vs.85%29.aspx#BC5). IOW, there is no blue channel to destroy :)

Thanks for posting it just the same.
