### ISSUE TITLE
Actions do not use presets correctly

### ISSUE THREAD

**Issue by QuietusPlus** [GameTechDev/ITW-Beta-Test#9]
Actions and scripts do not use presets correctly and instead seem to fall back on "-last-used-". I'm trying to automate saving a set of 3 textures without having to go through prompts. The order it should save in is:

1. Color (Preset 1)
2. Normal (Preset 2)
3. Normal (Preset 2)

The script listener adds `desc31.putString( idpres, """Preset 1/2""" );` but when executed saves using last settings (i.e. Color getting saved as Normal, or vise versa). It might also be worth noting that other UI/Input changes don't get captured, only the preset .

Not sure whether this is a fault within the plugin, feel free to close the issue if Photoshop itself is causing this.

**Script Sample**
Recorded using the Listener plugin (only the save path and idIntelDDS have been fixed/modified).
```
var idsave = charIDToTypeID( "save" );
    var desc18 = new ActionDescriptor();
    var idAs = charIDToTypeID( "As  " );
        var desc19 = new ActionDescriptor();
        var idpres = charIDToTypeID( "pres" );
        desc19.putString( idpres, """DDSExport_d""");
    var idIntelDDS = stringIDToTypeID( "Intel® Texture Works Intel® Texture Works" );
    desc18.putObject( idAs, idIntelDDS, desc19 );
    var idIn = charIDToTypeID( "In  " );
    desc18.putPath( idIn, new File( activeDocument.path + "\\DDSExport_d.DDS") );
    var idDocI = charIDToTypeID( "DocI" );
    desc18.putInteger( idDocI, 195 );
    var idCpy = charIDToTypeID( "Cpy " );
    desc18.putBoolean( idCpy, true );
    var idLyrs = charIDToTypeID( "Lyrs" );
    desc18.putBoolean( idLyrs, false );
    var idsaveStage = stringIDToTypeID( "saveStage" );
    var idsaveStageType = stringIDToTypeID( "saveStageType" );
    var idsaveSucceeded = stringIDToTypeID( "saveSucceeded" );
    desc18.putEnumerated( idsaveStage, idsaveStageType, idsaveSucceeded );
executeAction( idsave, desc18, DialogModes.NO );
```

**Comment by jawilli312** [comment]
Thanks for posting this, we're looking into it.

**Comment by jawilli312** [comment]
I believe we've resolved this in the latest build.
If you'd like to verify it yourself please [contact me](https://github.com/jawilli312).

**Comment by QuietusPlus** [comment]
Sent you a message via email regarding your reply.

**Comment by QuietusPlus** [comment]
Feel free to close this, fixed in the newer build.

**Comment by jawilli312** [comment]
Thank you
